"""initial schema

Revision ID: 5c0bcd4c8144
Revises:
Create Date: 2026-09-19 18:24:33.332360
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '5c0bcd4c8144'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('next_action', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_episodes'))
    )
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episodes_status'), ['status'], unique=False)

    op.create_table('idea_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idea_notes'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64, collation='NOCASE'), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tags.id'], name=op.f('fk_tags_parent_id_tags'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_parent_id'), ['parent_id'], unique=False)

    op.create_table('voices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voices')),
    sa.UniqueConstraint('file_path', name=op.f('uq_voices_file_path'))
    )
    op.create_table('episode_idea_notes',
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('idea_note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_episode_idea_notes_episode_id_episodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idea_note_id'], ['idea_notes.id'], name=op.f('fk_episode_idea_notes_idea_note_id_idea_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('episode_id', 'idea_note_id', name=op.f('pk_episode_idea_notes'))
    )
    with op.batch_alter_table('episode_idea_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episode_idea_notes_idea_note_id'), ['idea_note_id'], unique=False)

    op.create_table('episode_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_episode_notes_episode_id_episodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_episode_notes'))
    )
    with op.batch_alter_table('episode_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episode_notes_episode_id'), ['episode_id'], unique=False)

    op.create_table('episode_tags',
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_episode_tags_episode_id_episodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_episode_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('episode_id', 'tag_id', name=op.f('pk_episode_tags'))
    )
    with op.batch_alter_table('episode_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episode_tags_tag_id'), ['tag_id'], unique=False)

    op.create_table('episode_voices',
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('voice_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_episode_voices_episode_id_episodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_id'], ['voices.id'], name=op.f('fk_episode_voices_voice_id_voices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('episode_id', 'voice_id', name=op.f('pk_episode_voices'))
    )
    with op.batch_alter_table('episode_voices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episode_voices_voice_id'), ['voice_id'], unique=False)

    op.create_table('idea_note_tags',
    sa.Column('idea_note_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idea_note_id'], ['idea_notes.id'], name=op.f('fk_idea_note_tags_idea_note_id_idea_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_idea_note_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idea_note_id', 'tag_id', name=op.f('pk_idea_note_tags'))
    )
    with op.batch_alter_table('idea_note_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idea_note_tags_tag_id'), ['tag_id'], unique=False)

    op.create_table('timestamp_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voice_id', sa.Integer(), nullable=False),
    sa.Column('position_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['voice_id'], ['voices.id'], name=op.f('fk_timestamp_notes_voice_id_voices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timestamp_notes'))
    )
    with op.batch_alter_table('timestamp_notes', schema=None) as batch_op:
        batch_op.create_index('ix_timestamp_notes_voice_position', ['voice_id', 'position_ms'], unique=False)

    op.create_table('voice_tags',
    sa.Column('voice_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_voice_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_id'], ['voices.id'], name=op.f('fk_voice_tags_voice_id_voices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('voice_id', 'tag_id', name=op.f('pk_voice_tags'))
    )
    with op.batch_alter_table('voice_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_tags_tag_id'), ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_tags_tag_id'))

    op.drop_table('voice_tags')
    with op.batch_alter_table('timestamp_notes', schema=None) as batch_op:
        batch_op.drop_index('ix_timestamp_notes_voice_position')

    op.drop_table('timestamp_notes')
    with op.batch_alter_table('idea_note_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idea_note_tags_tag_id'))

    op.drop_table('idea_note_tags')
    with op.batch_alter_table('episode_voices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episode_voices_voice_id'))

    op.drop_table('episode_voices')
    with op.batch_alter_table('episode_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episode_tags_tag_id'))

    op.drop_table('episode_tags')
    with op.batch_alter_table('episode_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episode_notes_episode_id'))

    op.drop_table('episode_notes')
    with op.batch_alter_table('episode_idea_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episode_idea_notes_idea_note_id'))

    op.drop_table('episode_idea_notes')
    op.drop_table('voices')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_parent_id'))

    op.drop_table('tags')
    op.drop_table('settings')
    op.drop_table('idea_notes')
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episodes_status'))

    op.drop_table('episodes')
    # ### end Alembic commands ###
